### PR TITLE
Add XO Android example

### PR DESCRIPTION
**Pull request by eloaverona**
This PR adds an example of an Android client for the XO transaction processor. 
By running the app the user can see all games in state, see the current state for a particular game, make a move and create a new game.
The example is at ` examples/xo_android_client`

### CODE REVIEW

**Comment by boydjohnson** [comment]
Hey, @CarvalhoLeonardo and @arsulegai we made an XO Android example client. Do you want to take a look?

**Comment by CarvalhoLeonardo** [comment]
Hey, looks nice!

**Comment by CarvalhoLeonardo** [comment]
I'll spin up an image and review it as soon as possible!

**Comment by arsulegai** [comment]
> Hey, @CarvalhoLeonardo and @arsulegai we made an XO Android example client. Do you want to take a look?

Awesome, need some time to review

**Pull request merged**
